# Generated by Django 2.2.5 on 2021-10-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_picturemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturemodel',
            name='group',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='picturemodel',
            name='owner',
            field=models.CharField(default='', max_length=50),
        ),
    ]
