# Generated by Django 2.2.5 on 2021-10-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20211028_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='group',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
