# Generated by Django 2.2.5 on 2021-11-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_auto_20211028_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='title',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
